# Generated by Django 4.2.29 on 2026-04-01 00:37

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_remove_deployment_script'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_from',
            field=models.CharField(blank=True, help_text='From address used in outbound email (e.g. isotopeiq@example.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host',
            field=models.CharField(default='localhost', max_length=253),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_recipients',
            field=models.TextField(blank=True, help_text='Comma-separated list of recipient email addresses for notifications.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ftp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ftp_host',
            field=models.CharField(default='localhost', max_length=253),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ftp_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ftp_port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ftp_protocol',
            field=models.CharField(choices=[('ftp', 'FTP'), ('sftp', 'SFTP')], default='sftp', max_length=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ftp_remote_path',
            field=models.CharField(default='/', help_text='Remote directory path where baseline JSON files will be deposited.', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ftp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PostCollectionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('new_baseline', 'New Baseline Established'), ('drift_detected', 'Drift Detected'), ('always', 'Always (every successful collection)')], max_length=30)),
                ('destination', models.CharField(choices=[('syslog', 'Syslog'), ('email', 'Email'), ('ftp', 'FTP/SFTP')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_collection_actions', to='policies.policy')),
            ],
            options={
                'ordering': ['trigger', 'destination'],
                'unique_together': {('policy', 'trigger', 'destination')},
            },
        ),
    ]
