# Generated by Django 4.2.29 on 2026-04-05 23:14

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_systemsettings_email_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_attr_email',
            field=models.CharField(blank=True, default='mail', max_length=64),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_attr_first_name',
            field=models.CharField(blank=True, default='givenName', max_length=64),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_attr_last_name',
            field=models.CharField(blank=True, default='sn', max_length=64),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_bind_dn',
            field=models.CharField(blank=True, help_text='DN of the account used to bind for searches', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_bind_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_group_search_base',
            field=models.CharField(blank=True, help_text='Base DN for group searches (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_server_uri',
            field=models.CharField(blank=True, help_text='LDAP server URI, e.g. ldap://ldap.example.com:389', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_staff_group',
            field=models.CharField(blank=True, help_text='Full DN of the group whose members get Django staff access', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_start_tls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_superuser_group',
            field=models.CharField(blank=True, help_text='Full DN of the group whose members become Django superusers', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_user_search_base',
            field=models.CharField(blank=True, help_text='Base DN for user searches, e.g. ou=users,dc=example,dc=com', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ldap_user_search_filter',
            field=models.CharField(blank=True, default='(uid=%(user)s)', help_text='LDAP filter for user lookup', max_length=255),
        ),
    ]
