# Generated by Django 4.2.29 on 2026-06-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_systemsettings_agent_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcollectionaction',
            name='trigger',
            field=models.CharField(choices=[('new_baseline', 'New Baseline Established'), ('drift_detected', 'Drift Detected'), ('job_failed', 'Job Failed'), ('always', 'Always (every successful collection)')], max_length=30),
        ),
    ]
