# Generated by Django 4.2.29 on 2026-06-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_job_failed_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='device_offline_threshold_hours',
            field=models.PositiveIntegerField(default=48, help_text="Hours since a device's last successful collection before it is considered offline and a device_offline notification fires. 0 disables offline detection."),
        ),
    ]
