# Generated by Django 4.2.29 on 2026-03-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_data', models.JSONField()),
                ('established_at', models.DateTimeField(auto_now=True)),
                ('established_by', models.CharField(default='system', max_length=255)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='devices.device')),
                ('source_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_source', to='jobs.devicejobresult')),
            ],
            options={
                'ordering': ['device__name'],
            },
        ),
    ]
