# Generated by Django 4.2.29 on 2026-03-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('acknowledged_by', models.CharField(blank=True, max_length=255)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_events', to='devices.device')),
                ('job_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_events', to='jobs.devicejobresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
