# Generated by Django 4.2.29 on 2026-03-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftevent',
            name='acknowledgement_reason',
            field=models.TextField(blank=True),
        ),
    ]
