# Generated by Django 4.2.29 on 2026-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0002_acknowledgement_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftevent',
            name='baseline_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
