# Generated by Django 4.2.29 on 2026-03-29 17:19

from django.db import migrations, models


SEED_RULES = [
    # (section, spec_type, field_name, aux, description)
    ('filesystem',         'item_field',     'free_gb',                                    '',    'Disk free space changes constantly'),
    ('users',              'item_field',     'last_login',                                 '',    'Last login timestamp changes on every login'),
    ('users',              'item_field',     'password_last_set',                          '',    'Password timestamp changes on every change'),
    ('services',           'item_field',     'status',                                     '',    'Runtime service status; startup config is tracked'),
    ('listening_services', 'item_field',     'pid',                                        '',    'PID changes on every restart'),
    ('network',            'section_field',  'open_ports',                                 '',    'Open ports snapshot changes with active connections'),
    ('os',                 'section_field',  'ntp_synced',                                 '',    'NTP sync state is runtime, not configuration'),
    ('certificates',       'item_field',     'not_before',                                 '',    'Certificate validity window changes on renewal'),
    ('certificates',       'item_field',     'not_after',                                  '',    'Certificate expiry changes on renewal'),
    ('routing_protocols',  'nested_field',   'state',                                      'neighbors', 'BGP/OSPF neighbour session state is runtime'),
    ('vpn_tunnels',        'item_field',     'status',                                     '',    'VPN tunnel up/down state is runtime'),
    ('vlans',              'item_field',     'state',                                      '',    'VLAN operational state is volatile'),
    ('spanning_tree',      'section_field',  'root_bridge',                                '',    'STP root bridge changes on topology events'),
    ('spanning_tree',      'section_field',  'root_priority',                              '',    'STP root priority changes on topology events'),
    ('spanning_tree',      'section_field',  'root_address',                               '',    'STP root address changes on topology events'),
    ('spanning_tree',      'nested_field',   'role',                                       'ports', 'STP port role changes on topology events'),
    ('spanning_tree',      'nested_field',   'state',                                      'ports', 'STP port state changes on topology events'),
    ('sysctl',             'exclude_key',    'fs.dentry-state',                            'key', 'VFS dentry cache counter'),
    ('sysctl',             'exclude_key',    'fs.inode-state',                             'key', 'VFS inode cache counter'),
    ('sysctl',             'exclude_key',    'fs.file-nr',                                 'key', 'Open file descriptor count'),
    ('sysctl',             'exclude_key',    'fs.inode-nr',                                'key', 'Open inode count'),
    ('sysctl',             'exclude_key',    'kernel.ns_last_pid',                         'key', 'PID counter; increments with every fork'),
    ('sysctl',             'exclude_key',    'kernel.random.entropy_avail',                'key', 'Entropy pool level'),
    ('sysctl',             'exclude_key',    'kernel.random.write_wakeup_threshold',       'key', 'Entropy write threshold'),
    ('sysctl',             'exclude_key',    'kernel.random.uuid',                         'key', 'Random UUID; changes on every read'),
    ('sysctl',             'exclude_key',    'kernel.random.boot_id',                      'key', 'Boot ID UUID'),
    ('sysctl',             'exclude_key',    'net.netfilter.nf_conntrack_count',           'key', 'Active connection tracking count'),
    ('sysctl',             'exclude_key',    'net.netfilter.nf_conntrack_expect_count',    'key', 'Connection tracking expected count'),
    ('sysctl',             'exclude_key',    'fs.nfs.nfs_congestion_kb',                   'key', 'NFS runtime congestion counter'),
]


def seed_rules(apps, schema_editor):
    VolatileFieldRule = apps.get_model('drift', 'VolatileFieldRule')
    if VolatileFieldRule.objects.exists():
        return
    VolatileFieldRule.objects.bulk_create([
        VolatileFieldRule(
            section=section,
            spec_type=spec_type,
            field_name=field_name,
            aux=aux,
            description=description,
        )
        for section, spec_type, field_name, aux, description in SEED_RULES
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0003_add_baseline_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolatileFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('spec_type', models.CharField(choices=[('section_field', 'Section field — drop from section dict'), ('item_field', 'Item field — drop from each array item'), ('nested_field', 'Nested field — drop from nested array items'), ('exclude_key', 'Exclude item by key value')], max_length=30)),
                ('field_name', models.CharField(max_length=200)),
                ('aux', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'spec_type', 'field_name'],
                'unique_together': {('section', 'spec_type', 'field_name', 'aux')},
            },
        ),
        migrations.RunPython(seed_rules, migrations.RunPython.noop),
    ]
