# Generated by Django 4.2.29 on 2026-03-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0004_volatile_field_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volatilefieldrule',
            name='spec_type',
            field=models.CharField(choices=[('section_field', 'Section field — drop from section dict'), ('item_field', 'Item field — drop from each array item'), ('nested_field', 'Nested field — drop from nested array items'), ('exclude_key', 'Exclude item by key value'), ('exclude_section', 'Exclude section — omit entire section from comparison')], max_length=30),
        ),
    ]
