# Generated by Django 4.2.29 on 2026-05-19 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0012_remove_script_target_os'),
        ('drift', '0007_make_job_result_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volatilefieldrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='volatilefieldrule',
            name='script_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volatile_rules', to='scripts.scriptjob'),
        ),
        migrations.AlterField(
            model_name='volatilefieldrule',
            name='spec_type',
            field=models.CharField(choices=[('section_field', 'Section field — drop from section dict'), ('item_field', 'Item field — drop from each array item'), ('nested_field', 'Nested field — drop from nested array items'), ('exclude_key', 'Exclude item by key value'), ('exclude_section', 'Exclude section — omit entire section'), ('key_prefix', 'Exclude items whose key starts with prefix')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='volatilefieldrule',
            unique_together={('script_job', 'section', 'spec_type', 'field_name', 'aux')},
        ),
    ]
