# Generated by Django 4.2.29 on 2026-06-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0009_drift_event_job_result_set_null'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='driftevent',
            index=models.Index(fields=['device', 'status'], name='drift_drift_device__808e20_idx'),
        ),
        migrations.AddIndex(
            model_name='driftevent',
            index=models.Index(fields=['-created_at'], name='drift_drift_created_909537_idx'),
        ),
    ]
