# Generated by Django 4.2.29 on 2026-03-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('script_type', models.CharField(choices=[('collection', 'Collection'), ('parser', 'Parser'), ('deployment', 'Deployment')], max_length=20)),
                ('target_os', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS'), ('any', 'Any')], default='any', max_length=20)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScriptPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('target_os', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS'), ('any', 'Any')], default='any', max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_script', models.OneToOneField(blank=True, limit_choices_to={'script_type': 'collection'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_as_collector', to='scripts.script')),
                ('parser_script', models.OneToOneField(blank=True, limit_choices_to={'script_type': 'parser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_as_parser', to='scripts.script')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
