# Generated by Django 4.2.29 on 2026-03-29 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptpackage',
            name='deployment_script',
            field=models.OneToOneField(blank=True, limit_choices_to={'script_type': 'deployment'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_as_deployer', to='scripts.script'),
        ),
    ]
