# Generated by Django 4.2.29 on 2026-03-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_add_deployment_script_to_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptpackage',
            name='deployment_script',
        ),
    ]
