# Generated by Django 4.2.29 on 2026-04-07 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_agent_token'),
        ('scripts', '0003_remove_deployment_script_from_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cron_schedule', models.CharField(blank=True, help_text='5-field cron expression, e.g. "0 3 * * *".  Leave blank for ad-hoc only.', max_length=100)),
                ('enable_baseline', models.BooleanField(default=False, help_text='Save parsed result as the device baseline (requires parser_script).')),
                ('enable_drift', models.BooleanField(default=False, help_text='Compare parsed result against existing baseline and create DriftEvents.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='script',
            name='script_type',
            field=models.CharField(choices=[('collection', 'Collection'), ('parser', 'Parser'), ('deployment', 'Deployment'), ('utility', 'Utility')], max_length=20),
        ),
        migrations.CreateModel(
            name='ScriptJobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(default='manual', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('client_output', models.TextField(blank=True)),
                ('server_output', models.TextField(blank=True)),
                ('parsed_output', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_job_results', to='devices.device')),
                ('script_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scripts.scriptjob')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='scriptjob',
            name='client_script',
            field=models.ForeignKey(blank=True, help_text='Runs on the remote device via SSH/WinRM/Telnet.', limit_choices_to={'script_type': 'utility'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_client_script', to='scripts.script'),
        ),
        migrations.AddField(
            model_name='scriptjob',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='script_jobs', to='devices.device'),
        ),
        migrations.AddField(
            model_name='scriptjob',
            name='parser_script',
            field=models.ForeignKey(blank=True, help_text='Optional parser to transform output into canonical JSON.', limit_choices_to={'script_type': 'parser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_scriptjob_parser', to='scripts.script'),
        ),
        migrations.AddField(
            model_name='scriptjob',
            name='server_script',
            field=models.ForeignKey(blank=True, help_text='Runs on the satellite server.  Receives raw_output from the client step.', limit_choices_to={'script_type': 'utility'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_server_script', to='scripts.script'),
        ),
    ]
