# Generated by Django 4.2.29 on 2026-04-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_add_utility_scriptjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='script_type',
            field=models.CharField(choices=[('collection', 'Collection'), ('parser', 'Parser'), ('deployment', 'Deployment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='client_script',
            field=models.ForeignKey(blank=True, help_text='Runs on the remote device via SSH/WinRM/Telnet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_client_script', to='scripts.script'),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='parser_script',
            field=models.ForeignKey(blank=True, help_text='Parser script to transform output into canonical JSON.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_scriptjob_parser', to='scripts.script'),
        ),
        migrations.AlterField(
            model_name='scriptjob',
            name='server_script',
            field=models.ForeignKey(blank=True, help_text='Runs on the satellite server.  Receives raw_output from the client step.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_server_script', to='scripts.script'),
        ),
    ]
