# Generated by Django 4.2.29 on 2026-04-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_remove_utility_script_type'),
        ('policies', '0005_flatten_script_fks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScriptPackage',
        ),
    ]
