# Generated by Django 4.2.29 on 2026-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_remove_scriptjob_schedule_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='language',
            field=models.CharField(default='shell', max_length=30),
        ),
        migrations.AddField(
            model_name='script',
            name='run_on',
            field=models.CharField(choices=[('client', 'Client (remote device)'), ('server', 'Server (satellite)'), ('both', 'Both')], default='client', max_length=10),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_type',
            field=models.CharField(choices=[('collection', 'Collection'), ('parser', 'Parser'), ('deployment', 'Deployment'), ('utility', 'Utility')], max_length=20),
        ),
    ]
