# Generated by Django 4.2.29 on 2026-04-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_remove_scriptjobstep_run_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptjob',
            name='job_type',
            field=models.CharField(choices=[('baseline_collection', 'Baseline Collection'), ('compliance_audit', 'Compliance Audit'), ('remediation', 'Remediation'), ('discovery', 'Discovery'), ('data_export', 'Data Export'), ('maintenance', 'Maintenance'), ('notification', 'Notification'), ('custom', 'Custom')], default='custom', max_length=64),
        ),
    ]
