# Generated by Django 4.2.29 on 2026-04-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_add_job_type_to_scriptjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='target_os',
        ),
    ]
