# Generated by Django 4.2.29 on 2026-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data_days', models.PositiveIntegerField(default=90, help_text='Days to retain raw collection output. 0 = keep forever.')),
                ('parsed_data_days', models.PositiveIntegerField(default=365, help_text='Days to retain parsed canonical JSON. 0 = keep forever.')),
                ('job_history_days', models.PositiveIntegerField(default=180, help_text='Days to retain job records. 0 = keep forever.')),
                ('log_days', models.PositiveIntegerField(default=90, help_text='Days to retain job stdout/stderr logs. 0 = keep forever.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Retention Policy',
                'verbose_name_plural': 'Retention Policy',
            },
        ),
    ]
