# Generated by Django 4.2.29 on 2026-03-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cron_schedule', models.CharField(default='0 2 * * *', help_text='Cron expression: minute hour dom month dow', max_length=100)),
                ('start_time', models.TimeField(blank=True, help_text='Optional fixed start time (UTC) overriding cron hour/minute.', null=True)),
                ('delay_between_devices', models.PositiveIntegerField(default=0, help_text='Seconds to wait between executing each device in this policy.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_script', models.ForeignKey(blank=True, limit_choices_to={'script_type': 'collection'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_as_collector', to='scripts.script')),
                ('deployment_script', models.ForeignKey(blank=True, help_text='Optional deployment script run via the Deploy action.', limit_choices_to={'script_type': 'deployment'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_as_deployment', to='scripts.script')),
                ('devices', models.ManyToManyField(blank=True, related_name='policies', to='devices.device')),
                ('parser_script', models.ForeignKey(blank=True, limit_choices_to={'script_type': 'parser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_as_parser', to='scripts.script')),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['name'],
            },
        ),
    ]
