# Generated by Django 4.2.29 on 2026-03-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='collection_method',
            field=models.CharField(choices=[('agent', 'Agent Pull'), ('script', 'Script Execution')], default='script', help_text='How collection is performed: poll agent HTTP endpoint or run a script via SSH/WinRM/Telnet.', max_length=10),
        ),
    ]
