# Generated by Django 4.2.29 on 2026-03-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_remove_deployment_script_from_package'),
        ('policies', '0002_add_collection_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='collection_script',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='parser_script',
        ),
        migrations.AddField(
            model_name='policy',
            name='script_package',
            field=models.ForeignKey(blank=True, help_text='Collection Profile containing the collection + parser scripts. Required for Script Execution policies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='scripts.scriptpackage'),
        ),
    ]
