# Generated by Django 4.2.29 on 2026-03-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_replace_scripts_with_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='deployment_script',
        ),
    ]
