# Generated by Django 4.2.29 on 2026-04-07 02:31

from django.db import migrations, models
import django.db.models.deletion


def copy_scripts_from_package(apps, schema_editor):
    # ScriptPackage was already removed in scripts.0006 — nothing to copy.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_remove_utility_script_type'),
        ('policies', '0004_remove_deployment_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='collection_script',
            field=models.ForeignKey(blank=True, help_text='Runs on the remote device to gather raw data. Required for Script Execution policies.', limit_choices_to={'script_type': 'collection'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_as_collector', to='scripts.script'),
        ),
        migrations.AddField(
            model_name='policy',
            name='parser_script',
            field=models.ForeignKey(blank=True, help_text='Runs on the Satellite to transform raw output into canonical JSON.', limit_choices_to={'script_type': 'parser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_as_parser', to='scripts.script'),
        ),
        migrations.RunPython(copy_scripts_from_package, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='policy',
            name='script_package',
        ),
    ]
