# Generated by Django 4.2.29 on 2026-04-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_delete_scriptpackage'),
        ('policies', '0005_flatten_script_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='script_job',
            field=models.ForeignKey(blank=True, help_text='Script Job containing the collection and parser scripts to run. Required for Script Execution policies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='scripts.scriptjob'),
        ),
        migrations.RemoveField(
            model_name='policy',
            name='collection_script',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='parser_script',
        ),
    ]
