# Generated by Django 4.2.29 on 2026-03-27 16:58

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('credential_type', models.CharField(choices=[('ssh_password', 'SSH Username/Password'), ('ssh_key', 'SSH Key'), ('windows', 'Windows (WinRM)'), ('api_token', 'API Token')], max_length=20)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('private_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('token', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('fqdn', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('device_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS'), ('network', 'Network Device'), ('other', 'Other')], default='linux', max_length=50)),
                ('os_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS'), ('ios', 'Cisco IOS'), ('junos', 'Juniper JunOS'), ('other', 'Other')], default='linux', max_length=50)),
                ('connection_type', models.CharField(choices=[('ssh', 'SSH'), ('telnet', 'Telnet'), ('winrm', 'WinRM'), ('https', 'HTTPS/API'), ('push', 'Push (Device-Initiated)')], default='ssh', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('ssh_private_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('push_token', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('host_key', models.TextField(blank=True, help_text='SSH host public key (output of ssh-keyscan). Optional but strongly recommended — omitting disables host verification.')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.credential')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
