# Generated by Django 4.2.29 on 2026-03-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='credential_type',
            field=models.CharField(choices=[('password', 'Username / Password'), ('private_key', 'Username / Private Key'), ('api_token', 'API Token')], max_length=20),
        ),
    ]
