# Generated by Django 4.2.29 on 2026-06-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_agent_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='offline_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
