# Generated by Django 4.2.29 on 2026-06-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_add_device_heartbeat_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
