# Generated by Django 4.2.29 on 2026-06-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_stale_periodic_tasks'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicejobresult',
            index=models.Index(fields=['status', 'started_at'], name='jobs_device_status_6c8d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='devicejobresult',
            index=models.Index(fields=['started_at'], name='jobs_device_started_d02993_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at'], name='jobs_job_created_77460a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'started_at'], name='jobs_job_status_dd8212_idx'),
        ),
    ]
