#!/bin/bash
# IsotopeIQ Linux Agent Installer
# Installs the agent binary as a root-owned systemd service.
#
# Usage:  sudo bash linux_install.sh [path-to-binary]
#
# The binary is included in the ZIP downloaded from IsotopeIQ.
# Pass an explicit path only if placing the binary elsewhere.

set -euo pipefail

# Load defaults from agent.conf if it was bundled alongside this script.
# agent.conf is generated by the IsotopeIQ satellite when building the bundle
# and contains PORT and (optionally) SECRET lines.
PORT=9322
SECRET=""
_CONF="$(dirname "$0")/agent.conf"
if [ -f "$_CONF" ]; then
    _port_line=$(grep -m1 '^PORT=' "$_CONF" 2>/dev/null || true)
    [ -n "$_port_line" ] && PORT="${_port_line#PORT=}"
    _secret_line=$(grep -m1 '^SECRET=' "$_CONF" 2>/dev/null || true)
    [ -n "$_secret_line" ] && SECRET="${_secret_line#SECRET=}"
fi

read -r -p "Port to listen on [${PORT}]: " _INPUT_PORT
PORT="${_INPUT_PORT:-${PORT}}"
if ! [[ "$PORT" =~ ^[0-9]+$ ]] || [ "$PORT" -lt 1 ] || [ "$PORT" -gt 65535 ]; then
    echo "ERROR: Invalid port '${PORT}'." >&2
    exit 1
fi

# Pick the right binary name for this architecture
ARCH=$(uname -m)
case "$ARCH" in
    x86_64)    REMOTE_BINARY="linux_collector_amd64" ;;
    i686|i386) REMOTE_BINARY="linux_collector_i686"  ;;
    *)         REMOTE_BINARY="linux_collector_amd64" ;;
esac

# Locate binary — bundled in the ZIP alongside this script
if [ -n "${1:-}" ]; then
    BINARY="$1"
elif [ -f "./${REMOTE_BINARY}" ]; then
    BINARY="./${REMOTE_BINARY}"
elif [ -f "./linux_collector" ]; then
    BINARY="./linux_collector"
else
    echo "ERROR: Binary not found. Place ${REMOTE_BINARY} alongside this script." >&2
    exit 1
fi

INSTALL_PATH="/usr/local/bin/isotopeiq-agent"
UNIT_PATH="/etc/systemd/system/isotopeiq-agent.service"

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root (sudo)." >&2
    exit 1
fi

# Stop and remove any existing installation
if systemctl is-active --quiet isotopeiq-agent 2>/dev/null; then
    echo "Stopping existing isotopeiq-agent service..."
    systemctl stop isotopeiq-agent
fi
if systemctl is-enabled --quiet isotopeiq-agent 2>/dev/null; then
    systemctl disable isotopeiq-agent
fi
if [ -f "$UNIT_PATH" ]; then
    rm -f "$UNIT_PATH"
    systemctl daemon-reload
fi

echo "Installing binary → ${INSTALL_PATH}"
cp -f "$BINARY" "$INSTALL_PATH"
chmod 700 "$INSTALL_PATH"
chown root:root "$INSTALL_PATH"

_EXTRA_ARGS=""
[ -n "$SECRET" ] && _EXTRA_ARGS=" --secret ${SECRET}"

echo "Writing systemd unit → ${UNIT_PATH}"
cat > "$UNIT_PATH" <<UNIT
[Unit]
Description=IsotopeIQ Baseline Collection Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${INSTALL_PATH} --serve --port ${PORT}${_EXTRA_ARGS}
Restart=on-failure
RestartSec=30
User=root
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
StandardOutput=journal
StandardError=journal
NoNewPrivileges=yes
ProtectSystem=strict
ReadWritePaths=/tmp

[Install]
WantedBy=multi-user.target
UNIT

echo "Enabling and starting isotopeiq-agent.service"
systemctl daemon-reload
systemctl enable --now isotopeiq-agent.service

# Clean up temp download if we created one
true  # nothing to clean up — binary was bundled

echo ""
echo "Done.  Agent listening on 0.0.0.0:${PORT}"
[ -n "$SECRET" ] && echo "       Agent secret authentication enabled."
echo "Check status:  systemctl status isotopeiq-agent"
echo "View logs:     journalctl -u isotopeiq-agent -f"
